export const CLUB_CONFIGS = {
  'night-shift': {
    slug: 'night-shift',
    scope: 'club-music',
    name: 'Night Shift',
    kicker: 'Music Club · After Hours',
    tagline: 'Where the late shift trades headphones.',
    marqueeContent: '♪ NIGHT SHIFT ♪',
    caption: 'LIVE FROM A CROWDED BAR · 9:42 PM · TOKYO',
    backgroundColor: '#1a0f1e',
    accentColor: '#00f5d4',
    moodWarmColor: '#ff6b35',
    moodCoolColor: '#0084ff',
    neonSignText: 'LIVE MUSIC',
    bartenderPersonality: 'rocker',
    bartenderName: 'Doc',
    bartenderLines: [
      "what'll it be, friend?",
      '47 in tonight. packed house.',
      "the new pressing's already half gone.",
      "tape just dropped. side A's a riot.",
      'drinks are colder than the sound mix.',
    ],
    drinks: [
      { id: 'beer', name: 'Cold beer', emoji: '🍺' },
      { id: 'whiskey', name: 'Whiskey, neat', emoji: '🥃' },
      { id: 'shot', name: 'Tequila shot', emoji: '🍷' },
      { id: 'water', name: 'Water', emoji: '💧' },
    ],
    nowPlaying: { track: 'Nocturne 12 · Submerge Mix', artist: 'Submerge', progress: 0.42 },
    ambientSounds: ['drum-beat', 'guitar-riff', 'crowd-murmur'],
    members: [
      { name: 'Reni Q', top: '78%', left: '12%', activity: 0.85, msg: 'that drum break is unreal' },
      { name: 'Mara', top: '82%', left: '26%', activity: 0.3 },
      { name: 'Iggy', top: '76%', left: '40%', activity: 0.5, msg: 'okay tape 1 side a IS the year' },
      { name: 'K Honey', top: '84%', left: '55%', activity: 0.2 },
      { name: 'Vinyl Joon', top: '78%', left: '68%', activity: 0.4 },
      { name: 'Atlas', top: '82%', left: '82%', activity: 0.55, msg: 'submerge you legend' },
      { name: 'Polestar', top: '70%', left: '92%', activity: 0.2 },
    ],
    seedMessages: [
      { id: 1, author: 'DJ Echo', persona: 'dj', text: 'welcome back to the floor — fresh tape just dropped 🎧', intensity: 0.8 },
      { id: 2, author: 'Reni Q', persona: 'spotlight', text: "that drum break is unreal. who's the producer", intensity: 0.9 },
      { id: 3, author: 'Iggy', persona: 'member', text: 'okay tape 1 side a IS the year', intensity: 0.6 },
    ],
  },
  'velvet-reel': {
    slug: 'velvet-reel',
    scope: 'club-cinema',
    name: 'The Velvet Reel',
    kicker: 'Cinema Club · Late Show',
    tagline: 'Bring your favorite scene. Bring strong opinions.',
    marqueeContent: '▸ THE VELVET REEL ◂',
    caption: 'REEL 3 / SCENE 7 · MULHOLLAND DR. · 1:48 AM',
    backgroundColor: '#0a0505',
    accentColor: '#f72585',
    moodWarmColor: '#ff6b35',
    moodCoolColor: '#7c3aed',
    neonSignText: 'NOW PLAYING',
    bartenderPersonality: 'cinema-attendant',
    bartenderName: 'Mona',
    bartenderLines: [
      'house lights are coming down.',
      'fresh popcorn — three minutes.',
      "tonight's a slow build.",
      "balcony's still got two seats.",
      'the projector hates the cold.',
    ],
    drinks: [
      { id: 'wine', name: 'Red wine', emoji: '🍷' },
      { id: 'espresso', name: 'Double espresso', emoji: '☕' },
      { id: 'popcorn', name: 'Buttered popcorn', emoji: '🍿' },
      { id: 'soda', name: 'Cherry soda', emoji: '🥤' },
    ],
    nowPlaying: { track: 'Score · The Long Take', artist: 'Ennio Marc.', progress: 0.65 },
    ambientSounds: ['projector-click', 'orchestral-stab', 'popcorn-crunch'],
    members: [
      { name: 'Cassette', top: '76%', left: '16%', activity: 0.9, msg: 'that long take. brutal.' },
      { name: 'Lumen', top: '78%', left: '30%', activity: 0.3 },
      { name: 'Bea', top: '82%', left: '44%', activity: 0.5, msg: 'the score is doing 80% of the work' },
      { name: 'Reel', top: '76%', left: '58%', activity: 0.25 },
      { name: 'Mara', top: '80%', left: '72%', activity: 0.35, msg: 'why i fell in love with movies' },
      { name: 'Cinemax', top: '74%', left: '85%', activity: 0.2 },
    ],
    seedMessages: [
      { id: 1, author: 'The Usher', persona: 'dj', text: "house lights down. tonight's reel: a slow build, no spoilers.", intensity: 0.8 },
      { id: 2, author: 'Cassette', persona: 'spotlight', text: 'the way the camera holds on her face for those extra two seconds. brutal.', intensity: 0.85 },
      { id: 3, author: 'Bea', persona: 'member', text: 'the score is doing 80% of the work here', intensity: 0.5 },
    ],
  },
}
